#cloud-config

# SSH Settings
ssh_deletekeys: true
ssh_pwauth: false

# Users
disable_root: true
users:
  - default

# Default User
system_info:
  default_user:
    name: kube
    lock_passwd: true
    gecos: Default Kubernetes User
    groups: [wheel, docker]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash

# Delete Root Authorized Keys
runcmd:
  - ["rm", "-f", "/root/.ssh/authorized_keys"]
